version: '3.8'

services:

  backoffice-payment-frontend:
    image: backoffice-payment-frontend
    container_name: backoffice-payment-frontend
    build:
      context: .
      dockerfile: apps/backoffice-payment-frontend/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - message-api-service

  message-api-service:
    image: message-api-service
    container_name: message-api-service
    volumes:
      - ./volumes/h2:/data/h2
    environment:
      - H2_DB_PATH:/data/h2/bo-payment-routing-plateform
    build:
      context: .
      dockerfile: apps/message-api-service/Dockerfile
    ports:
      - "8080:8080"
