-- Insert or update partners
MERGE INTO partner (id, alias, type, direction, application, processed_flow_type, description)
KEY (id)
VALUES
  (1, 'swift-inbound', 'EXTERNAL', 'INBOUND', 'PaymentEngine', 'MESSAGE', 'SWIFT messages for interbank payment routing'),
  (2, 'sepa-clearing', 'VENDOR', 'INBOUND', 'LiquidityMonitor', 'NOTIFICATION', 'SEPA transactions to European clearing systems'),
  (3, 'fx-confirmation', 'INTERNAL', 'OUTBOUND', 'TradePlatform', 'MESSAGE', 'FX trade confirmation notifications'),
  (4, 'custody-alerts', 'EXTERNAL', 'INBOUND', 'AlertingDashboard', 'MESSAGE', 'Alerts to custody platform for settlement'),
  (5, 'instant-payments', 'EXTERNAL', 'INBOUND', 'AlertingDashboard', 'ALERTING', 'Instant payment processing for real-time settlements'),
  (6, 'treasury-ops', 'INTERNAL', 'OUTBOUND', 'FraudSystem', 'MESSAGE', 'Treasury operations interface'),
  (7, 'cb-notifier', 'EXTERNAL', 'INBOUND', 'PaymentEngine', 'MESSAGE', 'Central Bank integration'),
  (8, 'ach-core', 'VENDOR', 'OUTBOUND', 'LiquidityMonitor', 'NOTIFICATION', 'ACH clearing operations'),
  (9, 'payment-hub', 'VENDOR', 'OUTBOUND', 'LiquidityMonitor', 'MESSAGE', 'Payment routing and orchestration'),
  (10, 'liquidity-gateway', 'INTERNAL', 'INBOUND', 'PaymentEngine', 'ALERTING', 'Liquidity monitoring and optimization'),
  (11, 'sanctions-filter', 'VENDOR', 'OUTBOUND', 'AlertingDashboard', 'MESSAGE', 'Sanctions screening on outbound messages'),
  (12, 'aml-monitoring', 'EXTERNAL', 'OUTBOUND', 'TradePlatform', 'ALERTING', 'AML monitoring and suspicious activity detection'),
  (13, 'compliance-alerts', 'INTERNAL', 'OUTBOUND', 'CoreBankingSystem', 'MESSAGE', 'Compliance-related alerting and notifications'),
  (14, 'cb-integration', 'VENDOR', 'OUTBOUND', 'PaymentEngine', 'NOTIFICATION', 'Central Bank integration'),
  (15, 'trade-matching', 'INTERNAL', 'OUTBOUND', 'TradePlatform', 'NOTIFICATION', 'Trade matching notifications'),
  (16, 'reconciliation-engine', 'VENDOR', 'INBOUND', 'PaymentEngine', 'MESSAGE', 'Automated reconciliation processing'),
  (17, 'payment-tracker', 'INTERNAL', 'OUTBOUND', 'CoreBankingSystem', 'MESSAGE', 'Payment routing and orchestration'),
  (18, 'partner-onboarding', 'EXTERNAL', 'OUTBOUND', 'TradePlatform', 'ALERTING', 'Partner onboarding service'),
  (19, 'fraud-detection', 'INTERNAL', 'OUTBOUND', 'PaymentEngine', 'NOTIFICATION', 'Fraud detection and alerting'),
  (20, 'limit-checker', 'INTERNAL', 'INBOUND', 'AlertingDashboard', 'MESSAGE', 'Limit management system'),
  (21, 'credit-risk-system', 'INTERNAL', 'INBOUND', 'AlertingDashboard', 'MESSAGE', 'Credit risk control system'),
  (22, 'external-gateway', 'VENDOR', 'INBOUND', 'PaymentEngine', 'NOTIFICATION', 'External gateway integration'),
  (23, 'client-messaging', 'VENDOR', 'INBOUND', 'LiquidityMonitor', 'MESSAGE', 'Client messaging system'),
  (24, 'cash-pooling', 'EXTERNAL', 'OUTBOUND', 'PaymentEngine', 'MESSAGE', 'Cash pooling consolidation'),
  (25, 'nostro-monitor', 'EXTERNAL', 'OUTBOUND', 'LiquidityMonitor', 'MESSAGE', 'Nostro account monitoring'),
  (26, 'accounting-feed', 'VENDOR', 'OUTBOUND', 'CoreBankingSystem', 'MESSAGE', 'Accounting feed system'),
  (27, 'fee-calculation', 'VENDOR', 'OUTBOUND', 'FraudSystem', 'MESSAGE', 'Fee calculation and processing'),
  (28, 'routing-orchestrator', 'INTERNAL', 'OUTBOUND', 'FraudSystem', 'ALERTING', 'Routing rules orchestration engine'),
  (29, 'netting-engine', 'INTERNAL', 'OUTBOUND', 'LiquidityMonitor', 'MESSAGE', 'Netting engine for payment settlement'),
  (30, 'alerting-dashboard', 'EXTERNAL', 'INBOUND', 'FraudSystem', 'MESSAGE', 'Alert dashboard for operational monitoring');